In [ ]:
import numpy as np
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(names)



['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [ ]:
data

array([[ 0.12332163,  0.2618367 , -0.00903064,  0.27342903],
       [-0.49986308,  0.56005939,  0.33305436,  0.57212983],
       [-0.10383399,  0.55542389, -0.76626026,  0.74068478],
       [-0.62927911,  0.2133092 , -0.70071317,  0.90414522],
       [ 0.12502939, -1.98677442, -0.8088954 ,  1.47422102],
       [-0.38406229,  1.10636562,  0.39823385,  0.25373475],
       [ 0.68615539,  1.04864108, -1.16298785, -1.03186435]])

In [ ]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [ ]:
data[names=='Bob']

array([[ 0.12332163,  0.2618367 , -0.00903064,  0.27342903],
       [-0.62927911,  0.2133092 , -0.70071317,  0.90414522]])

In [ ]:
data[names=='Bob', 2:]

array([[-0.00903064,  0.27342903],
       [-0.70071317,  0.90414522]])

In [ ]:
data[names=='Bob',3:]#if we write only 3 then it print 3 cloumn row vise and
                      #if we write 3: then its print 3 coloumn

array([[0.27342903],
       [0.90414522]])

In [ ]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
data[~(names=='Bob')] #print value for names which is not eqaul to bob

array([[-0.49986308,  0.56005939,  0.33305436,  0.57212983],
       [-0.10383399,  0.55542389, -0.76626026,  0.74068478],
       [ 0.12502939, -1.98677442, -0.8088954 ,  1.47422102],
       [-0.38406229,  1.10636562,  0.39823385,  0.25373475],
       [ 0.68615539,  1.04864108, -1.16298785, -1.03186435]])

In [ ]:
data[names!='Joe']=7 #print the 7 where the name is not joe
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.49986308,  0.56005939,  0.33305436,  0.57212983],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.38406229,  1.10636562,  0.39823385,  0.25373475],
       [ 0.68615539,  1.04864108, -1.16298785, -1.03186435]])

**fancy indexing**

In [ ]:


arr = np.empty((8, 4))
for i in range(8):
  arr[i] = i
print(arr)  # Print only once, after the loop is finished


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [ ]:
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [ ]:
arr[[4,3,0,6]]#creating array as per the numbers given and before fancy indexing concept

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
arr=np.arange(32).reshape((8,4))
print(arr)#create array which contain 0 to 31 number and having 8 rows and 4 coloumn

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
# In [124]: arr[[1, 5, 7, 2], [0, 3, 1, 2]]
 #Out[124]: array([ 4, 23, 29, 10])


**transpose of array and swapping index**

In [ ]:
arr=np.arange(15).reshape((3,5))
print(arr)#creating array and reshape into 3 rows and 5 coloumn

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
arr.T#changing rows with column

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr=np.random.randn(6,3)
print(arr)

[[ 0.51032998 -0.07431068 -0.01474407]
 [-0.12546218  0.13402414 -1.04170879]
 [-0.21142552 -1.79245757  0.81152902]
 [ 1.00373096  1.6522564   1.27038126]
 [ 0.73140935 -1.09714576  0.00979074]
 [ 1.01695869  1.23100764 -0.54097929]]


In [ ]:
np.dot(arr.T,arr)#dot product of array and array transpose

array([[ 2.89751864,  2.43207549,  0.68372122],
       [ 2.43207549,  8.68544855, -0.17084577],
       [ 0.68372122, -0.17084577,  3.65057694]])

In [ ]:
arr=np.arange(16).reshape((2,2,4))
print(arr)# creating 3 dimension array which contain 2 element in x 2 in y and 4 in z

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
arr.transpose((1,0,2))#swapping index

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr.swapaxes(1,2)#swapping index x with y

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

**universal functions of numpy**

In [ ]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.sqrt(arr)#square root of array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)#exponent of array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
x=np.random.randn(8)
y=np.random.randn(8)
print(x)
print(y)
np.maximum(x,y)#print the maximum value between x and y

[ 2.11163405 -0.52624321 -1.32546084 -1.08133933  0.87538745  0.96138063
  0.02244975 -1.4406864 ]
[ 0.73342583  0.53960791  0.01642615 -0.09071474  0.59498756 -0.60916916
 -0.17484758  0.27139628]


array([ 2.11163405,  0.53960791,  0.01642615, -0.09071474,  0.87538745,
        0.96138063,  0.02244975,  0.27139628])

In [ ]:
arr=np.random.randn(7)*5
print(arr)
remainder,whole_part=np.modf(arr)
print(remainder)#give remainder
print(whole_part)# give whole part

[ 7.30892318 -4.22611165  5.91496383 -3.01578596 -2.92871858 -8.52297829
 -0.14610497]
[ 0.30892318 -0.22611165  0.91496383 -0.01578596 -0.92871858 -0.52297829
 -0.14610497]
[ 7. -4.  5. -3. -2. -8. -0.]


In [ ]:
arr

array([ 7.30892318, -4.22611165,  5.91496383, -3.01578596, -2.92871858,
       -8.52297829, -0.14610497])

In [ ]:
np.sqrt(arr) #negaative valuse doesn't give the sqrt value

<ipython-input-43-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([2.70350202,        nan, 2.43206987,        nan,        nan,
              nan,        nan])

In [ ]:
arr.mean()

-0.8022589210156442

In [ ]:
arr.sum()

-5.615812447109509

In [ ]:
arr=np.random.randn(5,4)
print(arr)

[[-3.78153894e-01  7.47682473e-01 -2.14951578e+00  4.92674740e-01]
 [ 2.05305186e+00 -1.36223917e+00 -1.63440632e+00 -1.13531062e-03]
 [-1.05043772e+00  1.83793532e+00 -6.20268573e-01 -6.56165681e-01]
 [-1.46789053e+00 -3.29812019e-01  8.83141682e-01 -3.53848447e-01]
 [ 1.65040894e-02 -1.34014678e+00 -6.83575258e-01  7.74682918e-02]]


In [ ]:
arr.mean(axis=1)#mean of rows

array([-0.32182812, -0.23618224, -0.12223416, -0.31710233, -0.48243742])

In [ ]:
arr.mean(axis=0)#mean of coloumn

array([-0.16538524, -0.08931603, -0.84092485, -0.08820128])

In [ ]:
arr.cumsum()#cummulative values

array([-0.37815389,  0.36952858, -1.7799872 , -1.28731246,  0.76573939,
       -0.59649977, -2.2309061 , -2.23204141, -3.28247913, -1.44454381,
       -2.06481238, -2.72097806, -4.1888686 , -4.51868061, -3.63553893,
       -3.98938738, -3.97288329, -5.31303007, -5.99660533, -5.91913704])

In [ ]:
(arr>0).sum()#calculate the number of positive vaslue

7

In [ ]:
bools=np.array([False,False,True,False])
bools.any()#check if any value is true
#bools.all()#check if all value is true

True

In [ ]:
arr=np.random.randn(6)
arr.sort()
print(arr)#sort function sort the array default in asecending order

[-2.31031896 -1.20097844  0.35152337  0.37016211  1.09825652  1.56171774]


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)#print unique value

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [ ]:
sorted(set(names))#YOU can sort a string by alfabetic order in python


['Bob', 'Joe', 'Will']

In [ ]:
import numpy as np#importing the numpy library as np
array=np.arange(100)#creating array using numpy
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
import numpy as np
data=np.random.randn(2,3)#creating an array which contain 2 row and 3 coloumn with random function menas contain and random number

print(data)

[[-0.48704862 -0.71637038 -0.01721161]
 [ 0.94861321 -1.74108608  0.44857686]]


In [ ]:
print(data*10)#multiplying array by 10

[[ -4.87048619  -7.16370378  -0.1721161 ]
 [  9.48613206 -17.41086083   4.48576855]]


In [ ]:
data+data#adding array with array bo

array([[-0.97409724, -1.43274076, -0.03442322],
       [ 1.89722641, -3.48217217,  0.89715371]])

In [ ]:
data.shape#display the array shape


(2, 3)

In [ ]:
data.dtype#display the data type of the array


dtype('float64')

In [ ]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.empty((2,3,2))#some times this function gives garbage value

array([[[1.65254696e-313, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [ ]:
float_arr=arr.astype(np.float64)#you can chnage the datatype by this way
float_arr.dtype

dtype('float64')

In [ ]:
arr.astype(np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
int_array=np.arange(10)
calibers=np.array([.22,.270,.376,.380,.44,.59],dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
empty_unit32=np.empty(8,dtype='u4')
empty_unit32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
arr2=np.array([[0,4,1],[7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [ ]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

**indexing and slicing**

In [ ]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8]=12

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_s=arr[5:8]
arr_s

array([12, 12, 12])

In [ ]:
arr_s[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_s[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [ ]:
arr2d[0][2]
arr2d[0,2]

3

In [ ]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
old_value=arr3d[0].copy()
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0]=old_value
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[1,0]

array([7, 8, 9])

In [ ]:
x=arr3d[1]
print(x)

[[ 7  8  9]
 [10 11 12]]


In [ ]:
x[0]

array([7, 8, 9])

**indexing with slicing**

In [ ]:
import numpy as np
arr=np.array([0,1,2,3,4,64,64,64,8,9])
print(arr)

[ 0  1  2  3  4 64 64 64  8  9]


In [ ]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])