In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression
import plotly.express as px
import plotly.graph_objects as go


In [2]:
x,y=make_regression(n_samples=100,n_features=2,noise=50,n_targets=1,n_informative=2)

In [3]:
df=pd.DataFrame({'feature1':x[:,0],'feature2':x[:,1],'target':y})

In [4]:
df.head()

feature1  feature2     target
0 -0.219255 -0.469951 -54.289332
1 -0.348088 -0.709540   1.941574
2 -0.865445  0.215879 -77.303841
3  0.897644 -1.922160  -7.186059
4 -0.223383 -2.325302 -28.280363

In [5]:
df.shape

(100, 3)

In [6]:
fig=px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.show()

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [8]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [9]:
y_pred=model.predict(x_test)

In [10]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
MAE=mean_absolute_error(y_test,y_pred)
MSE=mean_squared_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)

In [11]:
MAE


33.37012153815875

In [12]:
MSE

1583.814928899548

In [13]:
R2

0.7440904759559948

In [14]:
x=np.linspace(-5,5,10)
y=np.linspace(-5,5,10)
xGrid,yGrid=np.meshgrid(x,y)
z_final=model.predict(np.c_[xGrid.ravel(),yGrid.ravel()])
z_final=z_final.reshape(xGrid.shape)
final=np.vstack((xGrid.ravel(),yGrid.ravel(),z_final.ravel()))
fig=px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.add_traces(go.Surface(x=x,y=y,z=z_final))
fig.show()

In [15]:
model.coef_

array([78.75166709,  8.11634552])

In [16]:
model.intercept_

np.float64(-3.3134890301177746)

In [17]:
import numpy as np
from sklearn.datasets import load_diabetes

In [20]:
X,y=load_diabetes(return_X_y=True) #REMEBER X SHOULD BE CAPITAL

In [21]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [22]:
X.shape

(442, 10)

In [23]:
y.shape

(442,)

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [29]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [30]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [31]:
y_pred=reg.predict(X_test)

In [32]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4399338661568968

In [33]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [34]:
reg.intercept_

np.float64(151.88331005254167)

**making own code for multiple linear regression**

In [35]:
class mylr:
  def __init__(self):
    self.coef_=None
    self.intercept_=None

  def fit(self,X_train,y_train):
    X_train=np.insert(X_train,0,1,axis=1)

    # calculate the coeffs
    betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_=betas[0]
    self.coef_=betas[1:]
    print(betas)

  def predict(self,X_test):
    y_pred=np.dot(X_test,self.coef_) + self.intercept_
    return y_pred



In [62]:
LR=mylr()


In [63]:
LR.fit(X_train,y_train)

In [64]:
X_train.shape

(353, 10)

In [65]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [66]:
LR.predict(X_test)

In [69]:
print(LR.coef_)

None
